### ISSUE TITLE
Library Profiling Editing Rates

### ISSUE THREAD

**Issue by jamescrawf** [hkimlab/DeepPrime#1]
Hi!

Very nice study, congratulations! :)
I noticed that the editing rates for library profiling are missing from Table S2.
Would it be possible to upload them here on GitHub so people can get access to these as well?

Thanks a lot and congratulations again!
James

**Comment by Goosang-Yu** [comment]
Thank you for your interest in our research. 

It seems that we missed including the Profiling library information.  I have attached the raw file below. I hope it will be helpful for the research.

I apologize for the late response.

[Library-Profiling_raw.xlsx](https://github.com/hkimlab/DeepPrime/files/11595065/Library-Profiling_raw.xlsx)
