### ISSUE TITLE
KeyError: 'nAltIndex'

### ISSUE THREAD

**Issue by Shisheng-Huang** [hkimlab/DeepPrime#2]
Hi!
When I run the example, it got this error, can you see what's going on? Thanks!

python main_src.py main_run Analysis_Example
WARNING:tensorflow:From /public/home/yuwx/soft/miniconda3/lib/python3.9/site-packages/tensorflow/python/compat/v2_compat.py:107: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term

Start: Analysis_Example - PE2

Input subset range: 0 4
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/public/home/yuwx/soft/miniconda3/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/public/home/yuwx/soft/miniconda3/lib/python3.9/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/public/home/yuwx/soft/DeepPrime/main_src.py", line 368, in mp_processor
    deep_prime(analysistag, id, wtseq, editedseq, edit, dict_params, outdir)
  File "/public/home/yuwx/soft/DeepPrime/main_src.py", line 376, in deep_prime
    nAltIndex   = dict_params['nAltIndex']
KeyError: 'nAltIndex'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/public/home/yuwx/soft/DeepPrime/main_src.py", line 736, in <module>
    locals()[function_name](*function_parameters)
  File "/public/home/yuwx/soft/DeepPrime/main_src.py", line 134, in main_run
    p.map_async(mp_processor, parameters).get()
  File "/public/home/yuwx/soft/miniconda3/lib/python3.9/multiprocessing/pool.py", line 771, in get
    raise self._value
KeyError: 'nAltIndex'

**Comment by JulianeWeller** [comment]
Hi, 
I had the same issue. I got the example code running by making the following modifications:

**In main_src.py:**
replace
```
nAltIndex = dict_params['nAltIndex'] 
bTest = dict_params['bTest']
```
with
```
nAltIndex   = ALT_INDEX 
bTest       = bTEST
```
The variables are set at the beginning of the file and not in the parameter section, which is why it can't find the nAltIndex here.

***in dspcas9.py**
replace
```
best_model_path = '%s/bin/models/DeepSpCas9' % sBase_DIR
```
with
```
best_model_path = '%s/models/DeepSpCas9' % sBase_DIR
```
to update the paths

**in dprime.py**
replace depreciated squeeze option in pd.read_csv() and correct dir path
```
mean        = pd.read_csv('%s/%s/mean.csv' % (model_dir, model_type), header=None, index_col=0, squeeze = True)
std         = pd.read_csv('%s/%s/std.csv'  % (model_dir, model_type), header=None, index_col=0, squeeze = True)

model_dir  = '%s/bin/models' % sBase_DIR
```
with
```
mean        = pd.read_csv('%s/%s/mean.csv' % (model_dir, model_type), header=None, index_col=0).squeeze("columns")
std         = pd.read_csv('%s/%s/std.csv'  % (model_dir, model_type), header=None, index_col=0).squeeze("columns")

model_dir  = '%s/models' % sBase_DIR
```

It seems to work for me to run the example; but I'm not sure what the bTest and nAltIndex parameters are doing, I can't guarantee that those changes don't modify anything important ;) It would be great if the authors could have a look at this and solve the issue more permanently!

**Comment by Goosang-Yu** [comment]
I apologize for the delayed response. I will review the issue and work on resolving it as quickly as possible to update the source code.

If you would like to try using DeepPrime before that, we recommend using the Python package '[GenET](https://github.com/Goosang-Yu/genet)'. In particular, GenET is continuously being developed, and it provides faster issue response.

If you have any inquiries about GenET usage or encounter any critical errors, please contact us at [gsyu93@gmail.com](mailto:gsyu93@gmail.com).

Thank you.

**Comment by Goosang-Yu** [comment]
We have now updated the source code and ReadMe. Could you please check if it is functioning properly?

While the command-line version of DeepPrime has improved in terms of convenience, we still recommend using GenET.

I hope it works well in your environment.

Goosang

**Comment by Shisheng-Huang** [comment]
> We have now updated the source code and ReadMe. Could you please check if it is functioning properly?
> 
> While the command-line version of DeepPrime has improved in terms of convenience, we still recommend using GenET.
> 
> I hope it works well in your environment.
> 
> Goosang

I apologize for not promptly noticing your message. The new code is working well. Thank you.
