### ISSUE TITLE
 ends = seq[0] + seq[-1]  -- IndexError: string index out of range

### ISSUE THREAD

**Issue by j-fife** [hkimlab/DeepPrime#4]
I was able to run the example after altering the files described in [this](https://github.com/hkimlab/DeepPrime/issues/2) issue by [julianeweller](https://github.com/julianeweller). I've now created a file with 20 sequences and I receive the following error pasted below. It should be noted that all the sequences in question were able to run through the genet package, but I would like to be able to use the model in the error (PE2max_epegRNA_Opti_HEK293T). 

`

Start: my_test - PE2max_epegRNA_Opti_HEK293T

Input subset range: 0 20
MATPLOTLIB - Rank Plot - pegRNA1.2924
MATPLOTLIB - Rank Plot - pegRNA1.2999
MATPLOTLIB - Rank Plot - pegRNA1.2974
MATPLOTLIB - Rank Plot - pegRNA1.2899
MATPLOTLIB - Rank Plot - pegRNA1.2949
MATPLOTLIB - Rank Plot - pegRNA2.3799
MATPLOTLIB - Rank Plot - pegRNA2.3749
MATPLOTLIB - Rank Plot - pegRNA2.3849
MATPLOTLIB - Rank Plot - pegRNA2.3637
MATPLOTLIB - Rank Plot - pegRNA2.3687
MATPLOTLIB - Rank Plot - pegRNA3.2924
MATPLOTLIB - Rank Plot - pegRNA3.2999
MATPLOTLIB - Rank Plot - pegRNA3.2974
MATPLOTLIB - Rank Plot - pegRNA3.2899
MATPLOTLIB - Rank Plot - pegRNA3.2949
MATPLOTLIB - Rank Plot - pegRNA4.2924
MATPLOTLIB - Rank Plot - pegRNA4.2999
MATPLOTLIB - Rank Plot - pegRNA4.2974
MATPLOTLIB - Rank Plot - pegRNA4.2899
MATPLOTLIB - Rank Plot - pegRNA4.2949
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "[MY_PATH]/miniconda3/envs/genet/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "[MY_PATH]/miniconda3/envs/genet/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "main_src.py", line 368, in mp_processor
    deep_prime(analysistag, id, wtseq, editedseq, edit, dict_params, outdir)
  File "main_src.py", line 403, in deep_prime
    cFeat.determine_secondary_structure()
  File "[MY_PATH]/deepprime_repo/DeepPrime_src_wExamples/DeepPrime/src/biofeat.py", line 437, in determine_secondary_structure
    self.determine_Tm(sPAMKey, sSeqKey)
  File "[MY_PATH]/jf9645/deepprime_repo/DeepPrime_src_wExamples/DeepPrime/src/biofeat.py", line 452, in determine_Tm
    fTm1 = mt.Tm_NN(seq=Seq(sForTm1), nn_table=mt.R_DNA_NN1)
  File "[MY_PATH]/miniconda3/envs/genet/lib/python3.8/site-packages/Bio/SeqUtils/MeltingTemp.py", line 1021, in Tm_NN
    ends = seq[0] + seq[-1]
IndexError: string index out of range
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "main_src.py", line 739, in <module>
    locals()[function_name](*function_parameters)
  File "main_src.py", line 134, in main_run
    p.map_async(mp_processor, parameters).get()
  File "[MY_PATH]/miniconda3/envs/genet/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
IndexError: string index out of range

`

**Comment by Goosang-Yu** [comment]
Thank you for using DeepPrime. I appreciate your support. I will work to resolve any issues in the source code as soon as possible.

In the meantime, I would recommend using the [GenET package](https://github.com/Goosang-Yu/genet), which offers a much more user-friendly experience.

Have a great day!

Best regards,
Goosang

**Comment by Goosang-Yu** [comment]
We have now updated the source code and ReadMe. Could you please check if it is functioning properly?

While the command-line version of DeepPrime has improved in terms of convenience, we still recommend using GenET.

I hope it works well in your environment.

Goosang

**Comment by j-fife** [comment]
The new fixes work great! Thanks for the help.
