### ISSUE TITLE
NO OUTPUT 

### ISSUE THREAD

**Issue by YijiaChi** [hkimlab/DeepPrime#6]
Hello ,
I have run DeepPrime with ~10,000 rows csv in conda enviroment. About 1,000 of them couldn't generate output files. I tried several of theme in the web tool of DeepPrime, it showed an error:
![image](https://github.com/hkimlab/DeepPrime/assets/102590267/5a355af6-1a5b-4309-a0cd-fec80319ea60)
![image](https://github.com/hkimlab/DeepPrime/assets/102590267/b6e02b6b-2feb-486a-a91d-32a6497424a1)
However, the sequences do have the PAM sequences.

 

ID | RefSeq | Edited.Seq | EditType
-- | -- | -- | --
CDK4_region3_79_A_1_T | CTAAGAGGCCTAGATTTCCTTCATGCCAATTGCATCGTTCACCGAGATCTGAAGCCAGAGAACATTCTGGTGACAAGTGGTGGAACAGTCAAGCTGGCTGACTTTGGCCTGGCCAGAATCT | CTAAGAGGCCTAGATTTCCTTCATGCCAATTGCATCGTTCACCGAGATCTGAAGCCAGAGTACATTCTGGTGACAAGTGGTGGAACAGTCAAGCTGGCTGACTTTGGCCTGGCCAGAATCT | sub1

```bash

python DeepPrime.py -f HEK293T_input.csv -p PE4max-e \
--pbs_min 7 --pbs_max 14 --cell_type HEK293T -n HEK293T --progress --jobs 10
```
Any help would be greatly appreciated!

Sincerely,
Yijia

**Comment by Goosang-Yu** [comment]
Dear Yijia,

There are no suitable PAMs in these inputs, as indicated by the underlined PAM (AGG, position 6-8), which lacks a sufficient spacer length in front of it. For DeepPrime output to be generated, there should be an NGG (5'->3') within the left 40nt or a CCN (3'->5') within the right 40nt, based on the edit position (position +61, A>T).

The sequence you have currently input does not fulfill these criteria. If you wish to try DeepPrime with a different PAM, please select NRCH-PE and give it a try.

I hope your research goes well.

Goosang

**Comment by YijiaChi** [comment]
Thank you very much for your kind answer and helpful advice! 
･֊･
